name: cattle_breed_app
description: Cattle breed identification and farmer companion app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  image_picker: ^1.1.2
  provider: ^6.1.2
  web_socket_channel: ^2.4.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.1
  dio: ^5.5.0+1
  video_player: ^2.9.2
  chewie: ^1.7.5
  share_plus: ^7.2.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  timeago: ^3.6.1
  url_launcher: ^6.3.0
  flutter_image_compress: ^2.3.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/samples/



